# Generated by Django 5.0.6 on 2025-04-12 12:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Vertragstitel')),
                ('pdf_file', models.FileField(upload_to='contracts/', verbose_name='Vertragsdokument (PDF)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('creator_address', models.CharField(default=None, max_length=42, verbose_name='Ethereum-Adresse des Erstellers')),
                ('partner_address', models.CharField(default=None, max_length=42, verbose_name='Ethereum-Adresse des Partners')),
                ('creator_signature_x', models.FloatField(blank=True, null=True)),
                ('creator_signature_y', models.FloatField(blank=True, null=True)),
                ('creator_signature_width', models.FloatField(blank=True, null=True)),
                ('creator_signature_height', models.FloatField(blank=True, null=True)),
                ('creator_signature_page', models.IntegerField(blank=True, null=True)),
                ('partner_signature_x', models.FloatField(blank=True, null=True)),
                ('partner_signature_y', models.FloatField(blank=True, null=True)),
                ('partner_signature_width', models.FloatField(blank=True, null=True)),
                ('partner_signature_height', models.FloatField(blank=True, null=True)),
                ('partner_signature_page', models.IntegerField(blank=True, null=True)),
                ('is_configured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('uploaded', 'Hochgeladen'), ('configured', 'Konfiguriert'), ('invitation_sent', 'Einladung gesendet'), ('viewed_by_partner', 'Vom Partner angesehen'), ('partner_verified', 'Partner verifiziert'), ('signed_by_creator', 'Vom Ersteller unterschrieben'), ('signed_by_partner', 'Vom Partner unterschrieben'), ('completed', 'Vollständig unterschrieben'), ('blockchain_published', 'Auf Blockchain veröffentlicht'), ('rejected', 'Abgelehnt')], default='uploaded', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('blockchain_contract_id', models.BigIntegerField(blank=True, null=True, verbose_name='Blockchain-Vertrags-ID')),
                ('pdf_hash', models.CharField(blank=True, max_length=66, null=True, verbose_name='PDF-Hash')),
                ('blockchain_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='Blockchain-Status')),
                ('contract_amount', models.BigIntegerField(blank=True, null=True, verbose_name='Vertragsbetrag (Wei)')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Ersteller')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnered_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Partner')),
            ],
        ),
        migrations.CreateModel(
            name='ContractActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Vertrag erstellt'), ('upload', 'Vertrag hochgeladen'), ('configure', 'Vertrag konfiguriert'), ('send_invitation', 'Einladung gesendet'), ('view', 'Vertrag angesehen'), ('verify_partner', 'Partner verifiziert'), ('sign_creator', 'Vom Ersteller unterschrieben'), ('sign_partner', 'Vom Partner unterschrieben'), ('complete', 'Vertrag abgeschlossen'), ('reject', 'Vertrag abgelehnt'), ('status_change', 'Status geändert'), ('other', 'Sonstige Aktivität')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_address', models.CharField(blank=True, help_text='Ethereum-Adresse des Benutzers, der die Aktion ausgeführt hat', max_length=42, null=True)),
                ('user_role', models.CharField(choices=[('creator', 'Ersteller'), ('partner', 'Partner'), ('system', 'System')], default='system', max_length=10)),
                ('details', models.TextField(blank=True, help_text='Zusätzliche Details zur Aktivität', null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='contractsapp.contract')),
            ],
            options={
                'verbose_name': 'Vertragsaktivität',
                'verbose_name_plural': 'Vertragsaktivitäten',
                'ordering': ['-timestamp'],
            },
        ),
    ]
