# Generated by Django 5.0.6 on 2025-03-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='creator_address',
            field=models.CharField(default=None, max_length=42, verbose_name='Ihre Ethereum-Adresse'),
        ),
        migrations.AddField(
            model_name='contract',
            name='partner_address',
            field=models.CharField(default=None, max_length=42, verbose_name='Ethereum-Adresse des Vertragspartners'),
        ),
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('pending', 'Ausstehend'), ('accepted', 'Akzeptiert'), ('rejected', 'Abgelehnt'), ('completed', 'Abgeschlossen')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='contract',
            name='pdf_file',
            field=models.FileField(upload_to='contracts/', verbose_name='Vertragsdokument (PDF)'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Vertragstitel'),
        ),
    ]
