# Generated by Django 5.0.6 on 2025-05-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='delivery_oracle_confirmed',
            field=models.BooleanField(default=False, verbose_name='Von Oracle bestätigt'),
        ),
        migrations.AddField(
            model_name='contract',
            name='tracking_hash',
            field=models.CharField(blank=True, max_length=66, null=True, verbose_name='Tracking-Hash'),
        ),
    ]
