# Generated by Django 5.0.6 on 2025-06-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='tracking_hash',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Tracking-Hash'),
        ),
    ]
