# Generated by Django 5.0.6 on 2025-04-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractsapp', '0002_alter_contract_creator_alter_contract_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractactivity',
            name='action',
            field=models.CharField(choices=[('create', 'Vertrag erstellt'), ('upload', 'Vertrag hochgeladen'), ('configure', 'Vertrag konfiguriert'), ('send_invitation', 'Einladung gesendet'), ('view', 'Vertrag angesehen'), ('verify_partner', 'Partner verifiziert'), ('sign_creator', 'Vom Ersteller unterschrieben'), ('sign_partner', 'Vom Partner unterschrieben'), ('complete', 'Vertrag abgeschlossen'), ('reject', 'Vertrag abgelehnt'), ('status_change', 'Status geändert'), ('other', 'Sonstige Aktivität')], max_length=30),
        ),
    ]
