# Generated by Django 5.0.6 on 2025-06-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractsapp', '0002_update_tracking_hash_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Entwurf'), ('uploaded', 'Hochgeladen'), ('configured', 'Konfiguriert'), ('invitation_sent', 'Einladung gesendet'), ('viewed_by_partner', 'Vom Partner angesehen'), ('partner_verified', 'Partner verifiziert'), ('signed_by_creator', 'Vom Ersteller unterschrieben'), ('signed_by_partner', 'Vom Partner unterschrieben'), ('completed', 'Vollständig unterschrieben'), ('blockchain_published', 'Auf Blockchain veröffentlicht'), ('package_shipped', 'Paket versendet'), ('package_delivered', 'Paket geliefert'), ('delivery_confirmed', 'Lieferung bestätigt'), ('delivery_approved', 'Lieferung genehmigt'), ('agreement_fulfilled', 'Vereinbarung erfüllt'), ('rejected', 'Abgelehnt')], default='uploaded', max_length=20),
        ),
    ]
