# Generated by Django 5.0.6 on 2025-03-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractsapp', '0002_contract_creator_address_contract_partner_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='partner_email',
            field=models.EmailField(default=None, max_length=254, verbose_name='E-Mail des Vertragspartners'),
        ),
        migrations.AddField(
            model_name='contract',
            name='partner_name',
            field=models.CharField(default=None, max_length=100, verbose_name='Name des Vertragspartners'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='partner_address',
            field=models.CharField(blank=True, default=None, max_length=42, null=True, verbose_name='Ethereum-Adresse des Vertragspartners'),
        ),
    ]
