# Generated by Django 5.0.6 on 2025-03-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractsapp', '0003_contract_partner_email_contract_partner_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='creator_signature_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='creator_signature_page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='creator_signature_width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='creator_signature_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='creator_signature_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_configured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='partner_signature_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='partner_signature_page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='partner_signature_width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='partner_signature_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='partner_signature_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
