# Generated by Django 5.0.6 on 2025-04-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractsapp', '0003_alter_contractactivity_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='funds_withdrawn',
            field=models.BooleanField(default=False, verbose_name='Gelder wurden abgehoben'),
        ),
    ]
