# Generated by Django 5.0.6 on 2025-03-31 10:04

import contractsapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractsapp', '0004_contract_creator_signature_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='pdf_file',
            field=models.FileField(upload_to=contractsapp.models.contract_pdf_file_path, verbose_name='Vertragsdokument (PDF)'),
        ),
    ]
