# Generated by Django 5.0.6 on 2025-03-31 10:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractsapp', '0005_alter_contract_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='pdf_file',
            field=models.FileField(upload_to='contracts/', verbose_name='Vertragsdokument (PDF)'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Entwurf'), ('uploaded', 'Hochgeladen'), ('configured', 'Konfiguriert'), ('invitation_sent', 'Einladung gesendet'), ('viewed_by_partner', 'Vom Partner angesehen'), ('partner_verified', 'Partner verifiziert'), ('signed_by_creator', 'Vom Ersteller unterschrieben'), ('signed_by_partner', 'Vom Partner unterschrieben'), ('completed', 'Vollständig unterschrieben'), ('rejected', 'Abgelehnt')], default='uploaded', max_length=20),
        ),
        migrations.CreateModel(
            name='ContractActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Vertrag erstellt'), ('upload', 'Vertrag hochgeladen'), ('configure', 'Vertrag konfiguriert'), ('send_invitation', 'Einladung gesendet'), ('view', 'Vertrag angesehen'), ('verify_partner', 'Partner verifiziert'), ('sign_creator', 'Vom Ersteller unterschrieben'), ('sign_partner', 'Vom Partner unterschrieben'), ('complete', 'Vertrag abgeschlossen'), ('reject', 'Vertrag abgelehnt'), ('status_change', 'Status geändert'), ('other', 'Sonstige Aktivität')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_address', models.CharField(blank=True, help_text='Ethereum-Adresse des Benutzers, der die Aktion ausgeführt hat', max_length=42, null=True)),
                ('user_role', models.CharField(choices=[('creator', 'Ersteller'), ('partner', 'Partner'), ('system', 'System')], default='system', max_length=10)),
                ('details', models.TextField(blank=True, help_text='Zusätzliche Details zur Aktivität', null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='contractsapp.contract')),
            ],
            options={
                'verbose_name': 'Vertragsaktivität',
                'verbose_name_plural': 'Vertragsaktivitäten',
                'ordering': ['-timestamp'],
            },
        ),
    ]
