# Generated by Django 5.0.6 on 2025-04-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractsapp', '0006_contract_last_updated_alter_contract_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='blockchain_contract_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Blockchain-Vertrags-ID'),
        ),
        migrations.AddField(
            model_name='contract',
            name='blockchain_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Blockchain-Status'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_amount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Vertragsbetrag (Wei)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='pdf_hash',
            field=models.CharField(blank=True, max_length=66, null=True, verbose_name='PDF-Hash'),
        ),
        migrations.AddField(
            model_name='contract',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=66, null=True, verbose_name='Transaktions-Hash'),
        ),
    ]
