# Generated by Django 5.0.6 on 2025-04-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractsapp', '0007_contract_blockchain_contract_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='transaction_hash',
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Entwurf'), ('uploaded', 'Hochgeladen'), ('configured', 'Konfiguriert'), ('invitation_sent', 'Einladung gesendet'), ('viewed_by_partner', 'Vom Partner angesehen'), ('partner_verified', 'Partner verifiziert'), ('signed_by_creator', 'Vom Ersteller unterschrieben'), ('signed_by_partner', 'Vom Partner unterschrieben'), ('completed', 'Vollständig unterschrieben'), ('blockchain_published', 'Auf Blockchain veröffentlicht'), ('rejected', 'Abgelehnt')], default='uploaded', max_length=20),
        ),
    ]
