# Generated by Django 5.0.6 on 2025-04-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractsapp', '0008_remove_contract_transaction_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='partner_address',
            field=models.CharField(default=None, max_length=42, verbose_name='Ethereum-Adresse des Vertragspartners'),
        ),
    ]
